source 'https://github.com/ietstudio/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
# use_frameworks!

target 'AdvertiseUnityAds_Example' do
  pod 'AdvertiseUnityAds', :path => '../'
  pod 'UnityAds', '~> 1.5.6'
  target 'AdvertiseUnityAds_Tests' do
    inherit! :search_paths

    
  end
end
